config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/index'
  post 'home/save'

  #get 'welcome/index'

  get '/auth/spotify/callback', to: 'users#spotify'

  root 'welcome#index'
  # You can have the root of your site routed with "root"
  # root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'forecast_io'
  require 'omniauth'
  before_action :set_playlist, only: [:index, :save]

  def index
  	@summary = set_weather.currently.icon
  end

  private
  ForecastIO.configure do |configuration|
    configuration.api_key = ENV['FORECAST_CLIENT_ID']
  end

  def set_weather
	ForecastIO.forecast(37.3382, -121.8863)
  end

  def set_playlist
  	#Verify that we have current_user 
  	if params.has_key?(:save)

  	end
  	if params.has_key?("RSpotify::User")

	  	hash = params["RSpotify::User"][:hash]
	  	@user = RSpotify::User.new(hash)
	  	@current_weather = set_weather.currently.icon
	  	@theQuery = 'everyday music'

	  	case @current_weather
		  	when "clear-day"
		  		@theQuery = 'summer music'
		  	when "clear-night"
		  		@theQuery = 'night'
		  	when "rain"
		  		@theQuery = 'rainy weather'
		  	when "wind"
		  		@theQuery = 'cold weather'
		  	when "fog"
		  		@theQuery = 'foggy'
		  	when "cloudy"
		  		@theQuery = 'cloudy'
	  	end
	 
	  	@playlists_set = RSpotify::Playlist.search(@theQuery, limit: 50) #query should be adjusted to current weather
	  	ps_len = @playlists_set.count - 1
	 	@selected_list = @playlists_set[rand(0..ps_len)] #SELECT A RANDOM PLAYLIST

	 	@playlist_id = @selected_list.id
	 	@owner_id = @selected_list.owner.id

	 	@embed_link = "https://embed.spotify.com/?uri=spotify:user:" + @owner_id + ":playlist:" + @playlist_id
	
	#Otherwise, we must authorize the user again and generate a new playlist
 	else 
 	render "users/spotify"
 	end	
  		
  end

end

app/controllers/users_controller.rb
require 'omniauth'

class UsersController < ApplicationController
  def spotify
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    # Now you can access user's private data, create playlists and much more
    @hash = @spotify_user.to_hash
    #redirect_to :controller => "home", :action => "index", :hash => @hash, method: :post
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<%= button_to 'Sign out', 'https://www.spotify.com/logout/', method: :get%>

<h1><%= @summary %></h1>
<h1><%= @selected_list.name %></h1>

<iframe src=<%=@embed_link%> width="350" height="475" frameborder="0" allowtransparency="true"></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frosty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/spotify.html.erb
<%= form_for RSpotify::User.name, :url => home_index_path, :html => {:id => "hashForm"} do |f|%>
	<%= f.hidden_field :hash, :value => @hash %>
<%end%>

<h3>Generating playlist....</h3>

<script type="text/javascript">
$(document).ready(function(){
$("#hashForm").submit();
});
</script>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Sign in with Spotify', '/auth/spotify' %>